import React from 'react'
import Head from 'next/head'
import Footer from '@/components/Footer'

const conocenos = () => {
  return (
    <>
      <Head>
        <title>La Morocha - Conocenos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Conoce a quienes comforman nuestro gran equipo!" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="styles-sheets" href="../stylescomponents.css" />
      </Head>
      <div className='body-sobre-nosotros '>
        <div className="contenedor-nosotros">
          <h1>La Morocha</h1>
          <hr className='hrsobrenosotros' />
          <div className="cont-img-sobrenosotros">

            <img src="/lamorochalogo2.jpg" alt="lamorochalogo" />
          </div>
          <h2>como surgio?</h2>
          <div className="sobrenosotrosuno">
            <div className="hamburguesauno-nosotros">
              <img className='imguno mb-3' src="/8.jpg" alt="hamburguesa" />
              <img className='imguno mb-3' src="/ff.jpg" alt="hamburguesa" />
              <img className='imguno mb-3' src="/s.jpg" alt="hamburguesa" />
              <img className='imguno mb-3' src="/r.jpg" alt="hamburguesa" />
              </div>
              
            <div className="textouno">
              <p>Hola somos Nadia y Jony y queríamos contarles que  el  proyecto "La Morocha" comenzó en el año 2020 ,en  plena pandemia y con un país en una situación complicada , fue un tiempo muy difícil,  en el cual tuvimos que adaptarnos a las condiciones y restricciones que había en ese momento , empezó con una idea en conjunto con una pareja amiga  ( Mauri y Jaz ) que de paso aprovechamos para agradecerles por haber Sido parte de este emprendimiento desde un comienzo y felicitarlos también por haber podido abrir su propio negocio también gastronómico  que es sinónimo de crecimiento. Seguimos entonces con La Morocha Food Truck  contándoles  que comenzó como algo sencillo, para poder tener el plato de comida diario en casa y termino creciendo un poco mas todos los días , gracias a Dios en primer lugar y a nuestras familias , amigos , vecinos , conocidos y todos nuestros clientes que   hicieron y hacen que cada vez más La Morocha siga creciendo . 
</p></div>
          </div>
          <div className="sobrenosotrosdos">
            <div className="textodos">
              <p>El equipo de la morocha se basa en que nuestro producto se haga de una manera especial , como si se hiciera para uno mismo ,  todos queremos comer y degustar algo rico , por eso trabajamos con marcas de primera línea , y trabajamos materia prima de calidad , porque queremos que lo que se venda sea algo de otro nivel , algo que no pruebes en cualquier lado ...
Por otro lado contarles que trabajamos día a día para poder mejorar , para poder aprender más sobre esto tan lindo que es la gastronomía , contamos con 13 variedades diferentes de hamburguesas que es el fuerte de nosotros , y después por supuesto sandwiches, panchos , tostados , papas , aros de cebolla , milanesas al plato , etc ...
Hoy después de 3 años de trabajar en equipo estamos orgullosos de todo lo que se logró , y contentos porque sabemos que cada vez va a ir creciendo más .
Desde ya muchas gracias por querer conocernos y conocer nuestra historia .

El Equipo De La Morocha agradece a cada uno de ustedes por hacer esto posible</p></div>
            <div className="hamburguesdos-nosotros">
              <img className='mb-3' src="/o.jpg" alt="hamburguesa" />
              <img className='mb-3' src="/j.jpg" alt="hamburguesa" />
              <img className='mb-3' src="/q.jpg" alt="hamburguesa" />
              <img className='mb-3' src="/w.jpg" alt="hamburguesa" />
              </div>
          </div>
          <h2>Nuestro equipo</h2>
          <div className="equipocontenedor">
            <img src="/e.jpg" alt="empleado1" />
           
          </div>
        </div>


      </div>
      <Footer/>
    </>

  )
}

export default conocenos