import Head from 'next/head'
import React from 'react'

const contacto = () => {
    return (


        <>
            <Head>
                <title>La Morocha - contacto</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="styles-sheets" href="../stylescomponents.css" />
            </Head>
           
            <div className='body-contacto'>
            <div className="fondoprincipal">
            <h1>Contacto</h1>
                <div className="fondoredondo">
                <div className="fondoredondodos">
            <form className="form">
    <input className="input" type="text" placeholder="Nombre"/>
    <input className="input" type="text" placeholder="Email"/>
    <textarea className="textarea" placeholder="Escribe un mensaje"></textarea> 
    <center><button className="button">Enviar</button></center>
</form>   
</div>  </div>
            </div>
            </div>
        </>

    )
}

export default contacto