import Head from 'next/head'
import React from 'react'

const contacto = () => {
    return (


        <>
            <Head>
                <title>La Morocha - contacto</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="styles-sheets" href="../stylescomponents.css" />
            </Head>
           
            <div className='body-contacto'>
                 <p>1</p>   
            </div>
        </>

    )
}

export default contacto