import Head from 'next/head'
import React from 'react'

const contacto = () => {
    return (


        <>
            <Head>
                <title>La Morocha - contacto</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="styles-sheets" href="../stylescomponents.css" />
            </Head>
           
            <div className='body-contacto'>
            <h1>Contacto</h1>
          
            <div className="fondoprincipal">
                <p>Envianos tu reseña , que te parecio nuestro servivio ?</p>
                <input type="text" name="email" id="email"  placeholder='nombre'/>
              
             
         
 
            </div>
            </div>
        </>

    )
}

export default contacto