import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import Carouseles from '@/components/Carouseles';
import Ofertas from '@/components/Ofertas';


export default function Home() {
  return (
    <>
      <Head>
        <title>La Morocha - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="styles-sheets" href="../stylescomponents.css" />
      </Head>   
      <Carouseles/>
      <main>
        <Ofertas />
      </main>

    </>
  )
}
