import Head from 'next/head'
import React from 'react'

const login = () => {
    return (


        <>
            <Head>
                <title>La Morocha -login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="styles-sheets" href="../stylescomponents.css" />
            </Head>
            <div className='login-conteiner'>Iniciar sesion</div>
            <div class="login-box">
  <p>Iniciar sesion</p>
  <form>
    <div class="user-box">
      <input required="" name="" type="text"/>
      <label>Email</label>
    </div>
    <div class="user-box">
      <input required="" name="" type="password"/>
      <label>Contraseña</label>
    </div>
    <a href="#">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Enviar
    </a>
  </form>
 
</div>
        </>

    )
}

export default login