import Head from 'next/head'
import { useState } from 'react';
import swal from 'sweetalert';
import Cookies from 'universal-cookie';
import { logins } from '../helpers/auth';

const login = () => {



  const [password, setPassword] = useState("");
  const [message, setMessage] = useState([]);
  const [email, setEmail] = useState(" ");
  
  const handleSubmit = async (e) => {
    e.preventDefault();

    const datos = await logins({ email, password });
    
    const cookies = new Cookies();

    if (datos?.token) {

      cookies.set("token", `${datos.token}`, { path: "/", maxAge: 3850 });
      cookies.set("nombreUsuario", `${datos.token}`, { path: "/", maxAge: 3850 });



      swal(
        `Bienvenido ${datos.usuario.nombre}`,
        "Haz Clik para continuar!",
        "success"
      ).then((active) => {
        if (active) {
          location.replace("/admi");

        }
      });
    } else {
      if (datos?.errors) {
        setMessage(datos.errors);
      } else {
        setMessage([{ msg: datos.msg }]);
      }
    }
  };
    return (


        <>
            <Head>
                <title>La Morocha -login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="styles-sheets" href="../stylescomponents.css" />
            </Head>
            <div className='login-conteiner'>Iniciar sesion</div>
            <div className="login-box">
  <p>Iniciar sesion</p>
  <form onSubmit={handleSubmit}>
    <div className="user-box">
      <input required  name="email" type="email" value={email}
                      onChange={(e) => setEmail(e.target.value)}
      />
      <label>Email</label>
    </div>
    <div className="user-box">
                     
      <input required value={password}  onChange={(e) => setPassword(e.target.value)} name="pasword" type="password" />
      <label>Contraseña</label>
    </div>
    {message.length > 0 &&
              message.map((item, index) => (
                <div
                  key={index}
                  className="login__alertas   alert alert-danger "
                  role="alert"
                >
                  {item.msg}
                </div>
              ))}
    <button  >
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Enviar
    </button>
  </form>
 
</div>
        </>

    )
}

export default login