import Head from 'next/head'
import React from 'react'

const menus = () => {
    return (


        <>
            <Head>
                <title>La Morocha - Menus</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="styles-sheets" href="../stylescomponents.css" />
            </Head>
            <div>menus</div>
        </>

    )
}

export default menus